Models/MeetingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MeetingApp.Models
{
    public class MeetingInfo
    {
        public int ID { get; set; }
        public string? Location { get; set; }
        public DateTime Date { get; set; }
        public int NumberOfPeople { get; set; }
    }
}

Models/Repository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MeetingApp.Models
{
    public static class Repository
    {
        private static List<UserInfo> _users = new();
        public static List<UserInfo> Users
        {
            get
            {
                return _users;
            }
        }
        public static void CreateUser(UserInfo user)
        {
            user.Id = Users.Count + 1;
            _users.Add(user);
        }
        public static UserInfo? GetById(int id)
        {
            return _users.FirstOrDefault(user => user.Id == id);
        }
    }
}

Models/UserInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace MeetingApp.Models
{
    public class UserInfo
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Ad Alanı Zorunlu")]
        public string? Name { get; set; }
        [Required(ErrorMessage = "Telefon Alanı Zorunlu")]
        public string? Phone { get; set; }
        [Required(ErrorMessage = "Email Alanı Zorunlu")]
        [EmailAddress(ErrorMessage = "Email Geçerli Değil")]
        public string? Email { get; set; }
        [Required(ErrorMessage = "Katılım Alanı Zorunlu")]
        public bool? WillAttend { get; set; }
    }
}

Controllers/HomeController.cs
using MeetingApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace MeetingApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            int saat = DateTime.Now.Hour;
            ViewBag.Selamlama = saat > 12 ? "iyi Günler" : "Günaydın";

            var meetinginfo = new MeetingInfo()
            {
                ID = 1,
                Location = "İstanbul",
                Date = new DateTime(2024, 01, 20, 20, 0, 0),
                NumberOfPeople = Repository.Users.Where(i => i.WillAttend == true).Count(),


            };
            return View(meetinginfo);
        }
    }
}

Controllers/MeetingController.cs
using Microsoft.AspNetCore.Mvc;
using MeetingApp.Models;
namespace MeetingApp.Controllers

{
    public class MeetingController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }


        public IActionResult Apply()
        {
            var meetinginfo = new MeetingInfo()
            {
                ID = 1,
                Location = "İstanbul",
                Date = new DateTime(2024, 01, 20, 20, 0, 0),
                NumberOfPeople = 100,


            };
            return View();
        }

        [HttpPost]
        public IActionResult Apply(UserInfo model)
        {
            if (ModelState.IsValid)
            {
                Repository.CreateUser(model);
                ViewBag.UserCount = Repository.Users.Where(i => i.WillAttend == true).Count();
                return View("Thanks", model);
            }
            else
            {
                return View(model);
            }

        }

        public IActionResult List()
        {
            return View(Repository.Users);
        }

        public IActionResult Details(int id)
        {
            return View(Repository.GetById(id));
        }
    }
}

Views/Home/Index.cshtml
@model MeetingInfo
@{
ViewBag.Title = "Toplantı";
}
<main class="text-center">
    <h1 class="h4">Home Page</h1>
    <p>@ViewBag.Selamlama</p>
    <div class="card my-2">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">@Model.Location</li>
            <li class="list-group-item">@Model.Date.ToString("dd/MM/yyyy HH:mm:ss")</li>
            <li class="list-group-item">@Model.NumberOfPeople</li>
        </ul>
    </div>
    <a class="btn btn-sm btn-outline-primary" asp-controller="Meeting" asp-action="Apply">Başvur</a>

    <a class="btn btn-sm btn-outline-primary" asp-controller="Meeting" asp-action="List">Katılımcıları Listele</a>
</main>

Views/Meeting/Apply.cshtml
@model UserInfo
@{
ViewBag.Title = "Toplantı Başvuru";
}
<h1 class="h4">Toplantı Adı</h1>
<p>Toplantı Detayı</p>
<p>Toplantıya Katılan Kişi Sayısı: @ViewBag.UserCount</p>

<form method="post" action="/Meeting/Apply" novalidate>
    <div asp-validation-summary="All"></div>
    <div class="mb3">

        <label asp-for="Name" class="form-label">İsim</label>
        <input asp-for="Name" class="form-control">

    </div>
    <div class="mb-3">

        <label asp-for="Phone" class="form-label">Telefon Numarası</label>
        <input asp-for="Phone" class="form-control">

    </div>
    <div class="mb-3">

        <label asp-for="Email" class="form-label">Email</label>
        <input asp-for="Email" class="form-control">

    </div>
    <div class="mb-3">

        <label asp-for="WillAttend" class="form-label">Katılma Durumu</label>
        <select asp-for="WillAttend" class="form-select">
            <option value="">Seçiniz</option>
            <option value="true">Evet</option>
            <option value="false">Hayır</option>
        </select>

    </div>
    <button type="submit">Kaydet</button>
</form>

Views/Meeting/Details.cshtml
@model UserInfo
@{
ViewBag.Title = "Kişi Detay";
}

<main class="text-center">
    @{var durum=Model.WillAttend==true?"Katılıyor":"Katılmıyor";}
    <h1 class="h4">Katılımcı Detayı</h1>
    <p>İsim: @Model.Name</p>
    <p>Telefon Numarası: @Model.Phone</p>
    <p>Email: @Model.Email</p>
    <p>Katılım Durumu: @durum</p>
</main>

Views/Meeting/Index.cshtml
@{
ViewBag.Title = "Toplantı";
}
<main class="text-center">
    <h1>Toplantı Adı</h1>
    <p>Toplantı Detayı</p>
    <a href="#">Başvur</a>
</main>

Views/Meeting/List.cshtml
@model List<UserInfo>
    @{
    ViewBag.Title = "Katılımcı Listesi";
    }
    <h1 class="h4">Toplantı Adı</h1>
    <p>Toplantı Detayı</p>


    <table class="table table-bordered">
        <thead>
            <tr>
                <td>Ad</td>
                <td>Katılım Durumu</td>
                <td>Detay</td>
            </tr>
        </thead>
        <tbody>
            @{int i=0;}
            @foreach(var user in Model){
            var durum=user.WillAttend==true?"Evet":"Hayır";
            var className = user.WillAttend==true?"table-success":"table-danger";
            if(user.WillAttend==true){
            i++;
            }
            <tr class="@className">
                <td>@user.Name</td>
                <td>@durum</td>
                <td><a class="btn btn-sm btn-primary" href=/meeting/details/@user.Id>Deytay1</a></td>
            </tr>
            }

        </tbody>
    </table>
    <div class="card">
        <div class="card-body">
            <p>Toplantıya Katılan Kişi Sayısı: @i</p>
        </div>
    </div>

Views/Meeting/Thanks.cshtml
@model UserInfo
@{
ViewBag.Title = "Başvuru Durumu";
}
<main class="text-center">
    <h1>Başvuru Durmu</h1>
    @if(Model.WillAttend==true){
    <p>Teşekkürler @Model.Name, Toplantıya Sizinle Birlikte @ViewBag.UserCount Kişi Katılıyor</p>
    <a class="btn btn-sm btn-outline-primary" href="/meeting/list">Katılımcıları Listele</a>
    }
    else{
    <p>@Model.Name, Toplantımıza Katılmıyorsunuz</p>
    <a class="btn btn-sm btn-outline-primary" href="/meeting/apply">Başvuru Formu</a>
    }

</main>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css"
        integrity="sha512-t4GWSVZO1eC8BM339Xd7Uphw5s17a86tIZIj8qRxhnKub6WoyhnrxeCIMeAqBPgdZGlCcG2PrZjMc+Wr78+5Xg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="/css/styles.css" />
    <title>@ViewBag.Title - MeetingApp</title>
</head>

<body>
    <div class="bg-primary text-white p-2 text-center">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">MeetingApp</a>
    </div>
    <div class="container mt-3">
        <div class="row">
            <div class="col-lg-6 mx-auto ">
                <div class="card">
                    <div class="card-body">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>